language: go
sudo: false
before_install:
# Setup dependency management tool
- mkdir $GOPATH/bin/
- curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-darwin-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
before_script:
- go vet ./...
install:
- dep ensure
os:
- osx
go:
- tip
script:
- $HOME/gopath/src/github.com/britannic/pixelserv/testcoverage
env:
  global:
    secure: iZtmqGw9xdYullK4EBeTyr/u6+rCFIWpvJiGyEghIQbDIldd3mhgeeIPJzbHNB/Av/AiLWu7oE7Jm2CXbnGl/qzAZj62sNd2D+1ziInBnq55JwAtQUgWx2/794X1juhYzEjpR7alJvq0oC9dunOJU3RiRw4ND4sZFYl13i0003MhFZsvZwfGbG55jL95OW7pOBndAFyArQq3HOTVWGP43ZBB5YxEbnkjfMRW57jEQHBjZ+Gfr9ButgNvkURQ2UVQfNCer7tYLgxU1I9KDJCBeDLktrc8Pb43NW1/NE2ljFdEpjdJyvKvMy2yC41OgQdXs+vjjgmsGru7JZ3O+6NSTd89N+rly99LcLecePvwhDbF3VS+iL4RiunBf17bOTfAaNwMl5HH71iNq64329kDUzK34iEy76XUt7IM1/4GwquE/JC+TjW6rw2E5kJ1Yv3dgBxwsGSsPBDhep2j2oGNNp7DPlWic4gek9T48vwG58H52qf5+BFnl802hkDbh2VGYGCtKKuBce92Mz+djevQigynmaO+HsOKXQWU/TZbGA1AltH6FiKlUXAyP2J5E12QMVcymrWjNMPhmEi7dIMBZdRU6Wy+u5GQ9+4YXv8TMNqJYVCf7kTufXOm/wM+XDBmL4FeC6WZ8I4Y09MQ/3Ruqi6FBGdc23vU/f6IQHqPC+Q=
