#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

# Set up the Vyatta environment
declare -i DEC
source /opt/vyatta/etc/functions/script-template
OPRUN=/opt/vyatta/bin/vyatta-op-cmd-wrapper
CFGRUN=/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper
API=/bin/cli-shell-api
shopt -s expand_aliases

alias AddImage='${OPRUN} add system image'
alias begin='${CFGRUN} begin'
alias cleanup='${CFGRUN} cleanup'
alias comment='${CFGRUN} comment'
alias commit='${CFGRUN} commit'
alias copy='${CFGRUN} copy'
alias delete='${CFGRUN} delete'
alias DeleteImage='/usr/bin/ubnt-upgrade --delete-noprompt'
alias discard='${CFGRUN} discard'
alias end='${CFGRUN} end'
alias load='${CFGRUN} load'
alias rename='${CFGRUN} rename'
alias save='sudo ${CFGRUN} save'
alias set='${CFGRUN} set'
alias show='${API} showConfig'
alias showddns=/opt/vyatta/bin/sudo-users/vyatta-op-dynamic-dns.pl
alias version='${OPRUN} show version'

alias bold='tput bold'
alias normal='tput sgr0'
alias reverse='tput smso'
alias underline='tput smul'

alias black='tput setaf 0'
alias blink='tput blink'
alias blue='tput setaf 4'
alias cyan='tput setaf 6'
alias green='tput setaf 2'
alias lime='tput setaf 190'
alias magenta='tput setaf 5'
alias powder='tput setaf 153'
alias purple='tput setaf 171'
alias red='tput setaf 1'
alias tan='tput setaf 3'
alias white='tput setaf 7'
alias yellow='tput setaf 3'

# Setup the echo_logger function
echo_logger() {
	local MSG
	shopt -s checkwinsize
	COLUMNS=$(tput cols)
	DEC+=1
	CTR=$(printf "%03x" ${DEC})
	TIME=$(date +%H:%M:%S.%3N)

	case "${1}" in
	E)
		shift
		MSG="$(red)$(bold)ERRO$(normal)[${CTR}]${TIME}: ${@} failed!"
		;;
	F)
		shift
		MSG="$(red)$(bold)FAIL$(normal)[${CTR}]${TIME}: ${@}"
		;;
	FE)
		shift
		MSG="$(red)$(bold)CRIT$(normal)[${CTR}]${TIME}: ${@}"
		;;
	I)
		shift
		MSG="$(green)INFO$(normal)[${CTR}]${TIME}: ${@}"
		;;
	S)
		shift
		MSG="$(green)$(bold)NOTI$(normal)[${CTR}]${TIME}: ${@}"
		;;
	T)
		shift
		MSG="$(tan)$(bold)TRYI$(normal)[${CTR}]${TIME}: ${@}"
		;;
	W)
		shift
		MSG="$(yellow)$(bold)WARN$(normal)[${CTR}]${TIME}: ${@}"
		;;
	*)
		echo "ERROR: usage: echo_logger MSG TYPE(E, F, FE, I, S, T, W) MSG."
		exit 1
		;;
	esac

	# MSG=$(echo "${MSG}" | ansi)
	let COLUMNS=${#MSG}-${#@}+${COLUMNS}
	echo "post-install: ${MSG}" | fold -sw ${COLUMNS}
}

# Function to output command status of success or failure to screen and log
try() {
	if eval ${@}; then
		echo_logger I "${@}"
		return 0
	else
		echo_logger E "${@}"
		return 1
	fi
}

add_pseudo() {
	wanif=$(ip route get 8.8.8.8 | awk -F"dev " 'NR==1 {split($2,a," ");print a[1]}')
	if [[ "${wanif}" == *"pppoe"* ]]; then
		if echo ${wanif} | grep "pppoe"; then
			wanif=$(run show configuration commands | awk '/^set interfaces ethernet.*pppoe.*$/ {print $4; exit;}')
		fi
	fi

	/opt/vyatta/share/enumeration/existing-interfaces | grep peth0 &>/dev/null
	if [[ ${?} == 0 ]]; then
		echo_logger W "peth0 is already configured, you will need to set up a pseudo-ethernet interface with a different IP address"
		echo_logger I "In order to use pixelserv, a pseudo-ethernet interface is required, use these CLI commands:"
		echo -e "\tconfigure\n"
		echo -e "\tset service gui http-port 8180\n"
		echo -e "\tset interfaces pseudo-ethernet peth0 address <Unique IP Address>/<Subnet>\n"
		echo -e "\tset interfaces pseudo-ethernet peth0 description \"Pixel Server\"\n"
		echo -e "\tset interfaces pseudo-ethernet peth0 link <WAN Interface>\n"
		echo_logger I "Note: you can add any valid peth[x] interface. However, you must edit /etc/init.d/pixelserv and change the IP address for the listener"
		exit 0
	fi

	# ip=$(host $(hostname)| awk '{print $NF}')
	try begin
	# try set service gui listen-address ${ip}
	try set service gui http-port 8180
	try set interfaces pseudo-ethernet peth0 address 192.168.168.1/24
	try set interfaces pseudo-ethernet peth0 description '"Pixel Server"'
	try set interfaces pseudo-ethernet peth0 link ${wanif}
	try commit
	try save
	try end
}

fix_cfg_grp() {
	try chgrp -R vyattacfg /opt/vyatta/config/active
}

setup_init() {
	try chmod 0755 /etc/init.d/pixelserv
	try update-rc.d pixelserv defaults
}

start_pix() {
	/etc/init.d/pixelserv start
}

add_pseudo
fix_cfg_grp
setup_init
start_pix
